server:
  port: 9093

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server
spring:
  application:
    name: CLOUD-API
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: ADS-SERVICE
          uri: lb://ADS-SERIVCE
          predicates:
            - Path=/ads/**